"use strict";
const VERSION="portfolio-hub-v6";const STATIC=`${VERSION}-static`;const RUNTIME=`${VERSION}-runtime`;const PREFIX="portfolio-hub-";const CORE=["./","./index.html","./assets/css/style.css","./assets/js/app.js","./data/projects.json","./manifest.json","./assets/icons/icon-192.png","./assets/icons/icon-512.png"];
self.addEventListener("install",e=>e.waitUntil((async()=>{const c=await caches.open(STATIC);await Promise.allSettled(CORE.map(async x=>{try{const r=await fetch(new Request(x,{cache:"reload"}));if(r.ok)await c.put(x,r)}catch{}}));await self.skipWaiting()})()));
self.addEventListener("activate",e=>e.waitUntil((async()=>{for(const n of await caches.keys())if(n.startsWith(PREFIX)&&n!==STATIC&&n!==RUNTIME)await caches.delete(n);await self.clients.claim()})()));
const same=r=>{try{return new URL(r.url).origin===self.location.origin}catch{return false}},path=r=>{try{return new URL(r.url).pathname}catch{return""}},img=r=>r.destination==="image"||/\.(png|jpe?g|gif|webp|svg|ico)$/i.test(path(r));
async function put(cache,req,res){if(res&&res.ok&&res.type!=="opaque"){const c=await caches.open(cache);await c.put(req,res.clone())}}
async function networkFirst(req,cache=STATIC){try{const res=await fetch(req,{cache:"no-cache"});await put(cache,req,res);return res}catch(e){const cached=await caches.match(req);if(cached)return cached;throw e}}
async function cacheFirst(req){const c=await caches.match(req);if(c)return c;const r=await fetch(req);await put(RUNTIME,req,r);return r}
async function navigation(req){try{return await networkFirst(req,STATIC)}catch{const i=await caches.match("./index.html")||await caches.match("./");return i||new Response("<!doctype html><meta name=viewport content='width=device-width'><title>Offline</title><style>body{font-family:system-ui;display:grid;place-items:center;min-height:100vh;margin:0;background:#f8fafc;color:#0f172a}main{text-align:center;padding:24px}button{padding:10px 16px}</style><main><h1>You’re offline</h1><p>Reconnect to view the portfolio.</p><button onclick='location.reload()'>Try again</button></main>",{status:503,headers:{"Content-Type":"text/html"}})}}
self.addEventListener("fetch",e=>{const r=e.request;if(r.method!=="GET"||!/^https?:/.test(r.url)||!same(r))return;if(r.mode==="navigate"){e.respondWith(navigation(r));return}const p=path(r);if(p.endsWith("/assets/js/app.js")||p.endsWith("/assets/css/style.css")||p.endsWith("/data/projects.json")||p.endsWith("/manifest.json")){e.respondWith(networkFirst(r));return}if(img(r)){e.respondWith(cacheFirst(r));return}});
self.addEventListener("message",e=>{if(e.data?.type==="SKIP_WAITING")self.skipWaiting();if(e.data?.type==="CLEAR_CACHE")e.waitUntil((async()=>{for(const n of await caches.keys())if(n.startsWith(PREFIX))await caches.delete(n)})())});
